services:
  otp-token-api-db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - otp-token-api-db-postgres-volume:/var/lib/postgresql/data
    restart: always

volumes:
  otp-token-api-db-postgres-volume:
