### Create OTP Token

POST http://localhost:8080/api/otp/create
Content-Type: application/json

{
	"userId": "98e8b3dc-a923-4a98-9e26-36b2cf738892",
	"expiresInMinutes": 10
}

### Verify OTP Token
POST http://localhost:8080/api/otp/verify
Content-Type: application/json

{
	"tokenId": "f522c0ff-4460-4ec3-809b-4b8dcb1e6edb"
}


### Revoke OTP Token
DELETE http://localhost:8080/api/otp/revoke/f522c0ff-4460-4ec3-809b-4b8dcb1e6edb

### Health

GET http://localhost:8080/api/health


