name: AWS CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull brindocker/otp-pipeline:latest
      - name: Delete old Docker container
        run: sudo docker rm -f otp-pipeline-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name otp-pipeline-container brindocker/otp-pipeline:latest
