name: AWS CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull brindocker/otp-pipeline:latest
      - name: Delete old Docker container
        run: sudo docker rm -f otp-pipeline-container || true
      - name: Run Docker Container
        env:
          ENV: $ENV
          PORT: $PORT
          HOST: $HOST
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          sudo docker run -d \
            --name otp-pipeline-container \
            -e DATABASE_URL="$DATABASE_URL" \
            -e NODE_ENV="$NODE_ENV" \
            -e PORT="$PORT" \
            -e HOST="$HOST" \
            -p 8080:8080 \
            brindocker/otp-pipeline:latest
