name: Docker Image CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        env:
          ENV: $ENV
          PORT: $PORT
          HOST: $HOST
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: docker build -t brindocker/otp-pipeline:latest -f docker/Dockerfile .
      - name: Push to Dockerhub
        run: docker push brindocker/otp-pipeline:latest
